name: caesaria-gm # you probably want to 'snapcraft register <name>'
base: core22 # the base snap is the execution environment for this snap
version: '1.0.0' # just for humans, typically '1.2+git' or '1.3.2'
title: Caesaria
summary: Strategic simulation game where you step into the sandals of Julius Caesar.  # 79 char long summary
description: |
  Begin as a promising young politician in ancient Rome and navigate the treacherous waters of Roman politics, forging alliances, waging wars, and ultimately aiming to become the undisputed ruler of the Roman Empire.

grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots

apps:
  caesaria:
    command: bin/caesaria-bin
    extensions: [gnome]
    plugs:
      - network
      - unity7
      - network-status

layout:
  /usr/lib/${SNAPCRAFT_ARCH_TRIPLET}/webkit2gtk-4.1:
    bind: $SNAP/gnome-platform/usr/lib/$SNAPCRAFT_ARCH_TRIPLET/webkit2gtk-4.0

parts:
  caesaria:
    plugin: dump
    source: .
    organize:
      caesaria-bin: bin/
